services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb+srv://ms1577239:Mu20tSOhVH75dxW9@cluster0.yqwr16v.mongodb.net/task-management?retryWrites=true&w=majority&appName=Cluster0
    networks:
      - app-network

networks:
  app-network:
    driver: bridge